language: node_js
node_js:
  - "0.10.36"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g spacejam"
  - "npm install -g phantomjs2 --phantomjs_downloadurl=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
  - "export PATH=$PATH:$HOME/.meteor"

script: "spacejam test-packages ./ --use-system-phantomjs"
